default:
  image:
    name: rust:1.42.0
  tags:
    - shared-exec-docker

stages:
  - test
  - compile
  - build

cargo fmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

cargo test:
  stage: test
  script:
    - cargo test

publish dry run:
  stage: test
  before_script:
    - cargo login $CRATES_IO_TOKEN
  script:
    - cargo publish --dry-run

binary:
  stage: compile
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/metal-lion
    expire_in: 1h

docker:
  stage: build
  image: img.doom.fm/build/docker:latest
  before_script:
    - echo "FROM debian:stable\nCOPY target/release/metal-lion /bin/metal-lion\nENTRYPOINT [\"/bin/metal-lion\"]" > Dockerfile
  script:
    - sh /usr/local/bin/build-image