default:
  image:
    name: rust:1.48.0
  tags:
    - shared-exec-docker

stages:
  - test
  - build

cargo fmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

cargo test:
  stage: test
  script:
    - cargo test

publish dry run:
  stage: test
  before_script:
    - cargo login $CRATES_IO_TOKEN
  script:
    - cargo publish --dry-run

docker:
  stage: build
  image: img.doom.fm/build/docker:latest
  script:
    - sh /usr/local/bin/build-image