default:
  image:
    name: rust:1.42.0
  tags:
    - shared-exec-docker

stages:
  - test

cargo fmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

cargo test:
  stage: test
  script:
    - cargo test

publish dry run:
  stage: test
  before_script:
    - cargo login $CRATES_IO_TOKEN
  script:
    - cargo publish --dry-run